[bar]
order = [ "default" ]

    [bar.default]
    center = [ "workspaces" ]
    concave_edge_corners = false
    end = [ "tray", "status", "clock", "date" ]
    font_family = "Iosevka NFM"
    margin_ends = 0
    padding = 10
    radius = 0
    shadow = false
    start = [ "sysmon", "battery" ]
    thickness = 35
    widget_spacing = 5

[brightness]
minimum_brightness = 0.099999997764825821

[control_center]
hidden_tabs = [ "media", "monitor", "system", "power", "weather", "calendar", "notifications", "screen-time" ]

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "power_profile"

[location]
auto_locate = true

[lockscreen]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[osd]
offset_x = 50
offset_y = 50
position = "bottom_center"
position_vertical = "bottom_center"

[plugins]
enabled = [ "davemhammer/tailscale" ]

[shell]
font_family = "Iosevka NFM"
panel_anchor_bar = "default"
popup_shadows = false
settings_show_advanced = false

    [shell.animation]
    enabled = false

    [shell.panel]
    launcher_placement = "attached"
    shadow = false
    transparency_mode = "glass"

    [shell.screenshot]
    freeze_screen = false

    [shell.session]
    show_shortcuts = false

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "4"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "5"
        variant = "destructive"

    [shell.shadow]
    alpha = 0.0
    direction = "center"

[theme]
builtin = "Nord"
community_palette = "Monochrome"
custom_palette = "noctalia-wallpaper-dys"
source = "community"

[wallpaper]
enabled = false

    [wallpaper.default]
    path = "/nix/store/bcizdbjfzqiwhnshdz4cdmxzm2i1gwbc-noctalia-5.1.0/share/noctalia/assets/noctalia-wallpaper.png"

    [wallpaper.last]
    path = "/nix/store/bcizdbjfzqiwhnshdz4cdmxzm2i1gwbc-noctalia-5.1.0/share/noctalia/assets/noctalia-wallpaper.png"

[widget.status]
type = "davemhammer/tailscale:status"

[widget.sysmon]
stat = "ram_used"

[widget.workspaces]
active_pill_size = 2.0
pill_scale = 0.80000000000000004
show_labels = false
