#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ -d "$HOME/.local/bin" ] && [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    PATH="$PATH:$HOME/.local/bin"
fi

if [ -d "$HOME/.config/desktop-configs/config/shell/qs_bin" ] && [[ ":$PATH:" != *":$HOME/.config/desktop-configs/config/shell/qs_bin:"* ]]; then
    PATH="$PATH:$HOME/.config/desktop-configs/config/shell/qs_bin"
fi

export OMARCHY_PATH="$HOME/.config"
export PATH
