#!/bin/bash

# update nvim
rm -r $HOME/.config/dwmdesktop/Wayland/nvim
cp -r $HOME/.config/nvim $HOME/.config/dwmdesktop/Wayland/nvim

#update theme
rm -r $HOME/.config/dwmdesktop/Wayland/matte-black
cp -r $HOME/.config/omarchy/themes/matte-black/ $HOME/.config/dwmdesktop/Wayland/matte-black

#update python
rm -r $HOME/.config/dwmdesktop/Wayland/python $HOME/.config/dwmdesktop/X11/Scripts/python
cp -r $HOME/Work/python $HOME/.config/dwmdesktop/Wayland/python
cp -r $HOME/Work/python $HOME/.config/dwmdesktop/X11/Scripts/python

#update python
rm -r $HOME/.connfig/dwmdesktop/Wayland/mpip $HOME/.config/dwmdesktop/X11/Scripts/mpip
cp -r $HOME/.local/bin/mpip $HOME/.config/dwmdesktop/Wayland/mpip
cp -r $HOME/Work/mpip $HOME/.config/dwmdesktop/X11/Scripts/mpip

#updatestartship
rm $HOME/.config/dwmdesktop/Wayland/starship.toml
cp $HOME/.config/starship.toml $HOME/.config/dwmdesktop/Wayland/starship.toml

#updates desc
rm $HOME/.config/dwmdesktop/Wayland/update_desc
cp $HOME/.local/bin/update_desc $HOME/.config/dwmdesktop/Wayland/update_desc

#update mpip

